### ISSUE TITLE
Criar JSON com informações de Issues por Usuário

### ISSUE THREAD

**Issue by lucasmidlhey** [fga-eps-mds/2019.2-Git-Breakdown#100]
Eu como **desenvolvedor**, desejo **gerar um JSON com ranking de issues**, por **usuario**.

- Checklist:
 - [x] Coletar dados; 

  Filtrar dados relevantes:
 - [x] Abrir;
 - [x] Fechar;  
 - [x] Comentar; 
---
 - [x] Retornar JSON;
 - [x] Testes unitários.

**Comment by jbisinotti** [comment]
A issue está quase pronta, faltam apenas os testes unitários. :bulb:
