### ISSUE TITLE
Refatorar requisições para o Github

### ISSUE THREAD

**Issue by jbisinotti** [fga-eps-mds/2019.2-Git-Breakdown#104]
Eu como **desenvolvedor**, desejo **adicionar o atributo per_page, com um valor alto, ao queryString de todas as requisições para o Github**, para **que não haja limitações quanto ao número de informações requisitadas**.

- Checklist:
 - [x] alterar requisição de Issues
 - [x] alterar requisição de Commits
 - [x] alterar requisição de PR's
 - [x] alterar requisição de Branches

**Comment by lucasmidlhey** [comment]
Esta Issue foi criada para adiantar um serviço pre definido para esse sprint
