### ISSUE TITLE
Visualizar ranking de contribuição dos desenvolvedores

### ISSUE THREAD

**Issue by wdresende** [fga-eps-mds/2019.2-Git-Breakdown#118]
Eu como **Desenvolvedor**, desejo **visualizar um ranking de pontos dos contribuidores de certo repositório**, para **saber quais foram os maiores contribuidores para o repositório**.

- Checklist:
 - [ ] coletar dados de pontuação por usuário
 - [ ] tratar dados
 - [ ] criar página do ranking
 - [ ] mostrar o ranking

**Comment by wdvictor** [comment]
Due it the changes in sprints, the #118 issue is in developing in #143
