### ISSUE TITLE
Criar Documento de Arquitetura

### ISSUE THREAD

**Issue by pdaniel37** [fga-eps-mds/2019.2-Git-Breakdown#12]
Planejar e desenvolver o documento de arquitetura.

Este documento deve ter:

- [x] Introdução
- [x] Representação de Arquitetura
- [x] Metas e Restrições da Arquitetura
- [x] Visão de Casos de Uso
- [x] Visão Lógica

Documentos para usar como base:
- https://fga-eps-mds.github.io/2019.1-Aix/projeto/2019/03/29/documento-de-arquitetura/

**Comment by lucasmidlhey** [comment]
Ficou como pendencia para sprint 3
