### ISSUE TITLE
Personalizar página de popup

### ISSUE THREAD

**Issue by wdresende** [fga-eps-mds/2019.2-Git-Breakdown#140]
Eu como **desenvolvedor**, desejo **personalizar a página de popup**, para que seja possível **visualizar informações da extensão.**

- [x] Criar Descrição da aplicação
- [x] Reconfigurar o layout
- [x] Criar uma experiencia

**Comment by paulohgontijoo** [comment]
experiencia com o usuario se baseia em apertar o botao e ir ao git pages
