### ISSUE TITLE
Consertar bug da página do Github

### ISSUE THREAD

**Issue by wdresende** [fga-eps-mds/2019.2-Git-Breakdown#148]
Eu como desenvolvedor, desejo consertar o bug na página do github para que não haja mais conflitos do projeto com a página principal do github

**Comment by wdvictor** [comment]
O "bug" referente a essa issue, vem apartir do bootstrap. O GBD usa o Bootstrap no front,e o arquivo comprimido do bootstrap está alterando o comportamento padrão de alguns elementos dentro do GitHub. Até o momento, não foi possível achar uma solução para esse bug sem que tenhamos que retirar o bootstrap

**Comment by wdvictor** [comment]
The solution: 
    Once that the bootStrap override the GitHub default style, we are making the reverse engineering: make the GitHub default style override the bootstrap.
    But to do so, how GBD is adding bootstrap to the GitHub, the GBD need to add the GitHub styles into the page again to override the bootstrap where the bootstrap is not needed
