### ISSUE TITLE
Realizar reunião semanal 07/09

### ISSUE THREAD

**Issue by omateusp** [fga-eps-mds/2019.2-Git-Breakdown#16]
### Descrição
Nesta reunião iremos trabalhar com product backlog, sprint review e sprint plaining.

Foi definido:
- 1 hora pra sprint review
-  2 horas product backlog
- 1 hora pra sprint plaining

- [x] Sprint review

- [x] Product backlog

- [x] Sprint plaining

**Comment by lucasmidlhey** [comment]
Editar essa issue pois ja existia uma igual

**Comment by lucasmidlhey** [comment]
Reuniao relizada onde foi feita sprint review, plaining e o baclog da sprint
