### ISSUE TITLE
Refatorar microsserviços

### ISSUE THREAD

**Issue by jbisinotti** [fga-eps-mds/2019.2-Git-Breakdown#161]
**Eu como** desenvolvedor **desejo** refatorar os microsserviços **para** melhorar a qualidade do código, reduzir a complexidade das funções.

 * _Checklist:_
  - [x]  Branches
  - [x] Commits
  - [x] Issues
  - [x] Pullrequests

**Comment by paulohgontijoo** [comment]
two firsts commits was about branches api
