### ISSUE TITLE
Esquematizar versão inicial do pipeline de desenvolvimento

### ISSUE THREAD

**Issue by omateusp** [fga-eps-mds/2019.2-Git-Breakdown#17]
Diagramar o "caminho" do código desde a concepção da ideia até a sua entrega ao usuário

**Comment by lucasmidlhey** [comment]
Estamos buscando ajuda com outros grupos que fizeram algum aplicativo semelhante

**Comment by lucasmidlhey** [comment]
Depois de feito o deploy, será feito o pipeline de maneira clara e visual para o restante do grupo
