### ISSUE TITLE
Criar ambiente de desenvolvimento com Docker

### ISSUE THREAD

**Issue by wdresende** [fga-eps-mds/2019.2-Git-Breakdown#19]
Todos os integrantes do grupo devem ter o ambiente definido com docker e docker-compose em suas máquinas para o desenvolvimento do projeto.

- [x] Instalar docker e docker-compose
- [x] configurar tecnologia com o docker
- [x] Dar início ao projeto

**Comment by omateusp** [comment]
pra quem não baixou o docker ainda: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by pdaniel37** [comment]
@lucasmidlhey, @wdresende e @omateusp, na minha visão as tasks reservadas para MDS seriam:
- Instalar docker e docker-compose

E após a configuração do docker pelo DevOps:
- Baixar a imagem que tem os containers necessários
- Rodar o ambiente com o comando `docker-compose up`

**Comment by lucasmidlhey** [comment]
mas basicamente está assim a task @pdaniel37, baixar docker e docker-compose, logo apos o devops ira configurar.

**Comment by pdaniel37** [comment]
Issue finalizada no commit 5a979a9 e teve seu PR(#39) aceito.
