### ISSUE TITLE
Treinar conhecimentos sobre a api do GitHub

### ISSUE THREAD

**Issue by omateusp** [fga-eps-mds/2019.2-Git-Breakdown#20]
Cada integrante de mds deve tentar coletar as informações de repositórios para treinamento de acordo com a tecnologia escolhida para o desenvolvimento.

Todo integrante deve criar uma branch e trabalhar em um método de coleta de dados do GitHub

- [x] Victor Hugo
- [x] Paulo Henrique
- [x] Pedro Daia
- [x] João Victor
- [x]  Pedro Daniel

**Comment by wdvictor** [comment]
Pra quem ta com dúvida de onde começar com o Nodejs, acesse a branch feat#20/first_steps,
no diretório JS cheat sheet/Creating Node app/ para alguns esclarecimentos.

**Comment by pdaniel37** [comment]
Na minha branch 'feat#20/pdaniel', eu fiz uma API utilizando Express e em seguida fiz uma requisição para a API do GitHub, e passei o response em uma endpoint da minha API. Se eu tiver tempo, pretendo implementar o login utilizando OAuth2.0 para complementar os estudos, segue as referências utilizadas:
[Ensina criar API com Express](https://medium.com/@programadriano/criando-uma-api-node-em-10-passos-com-express-js-52b2d612a8a9)
[Ensina a fazer requests usando Node](https://medium.com/trainingcenter/brincando-com-uma-api-simples-em-node-js-8c1a50c7aab3)
[Documentação da GitHub API v3](https://medium.com/trainingcenter/brincando-com-uma-api-simples-em-node-js-8c1a50c7aab3)
