### ISSUE TITLE
US04 - Coletar informações de PR

### ISSUE THREAD

**Issue by omateusp** [fga-eps-mds/2019.2-Git-Breakdown#24]
Eu, como **desenvolvedor**, desejo **coletar informações de Pull Requests enviadas e aceitas**, para **que seja feita uma analise de features aceitas.**

- [x] Criar uma API (microsserviço)
- [x] Fazer requisições na API do GitHub
- [x] Usar parâmetros no endpoint
- [x] Testes Unitários

**Comment by pdaniel37** [comment]
A issue foi finalizada com a aceitação do PR(#37).
