### ISSUE TITLE
Criar protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by omateusp** [fga-eps-mds/2019.2-Git-Breakdown#25]
Cada integrante de MDS deverá produzir um protótipo de baixa fidelidade.

- [x] Pedro Daniel
- [x] Victor Antunes
- [x] Paulo Henrique
- [x] Pedro Daia
- [x] João Victor

**Comment by lucasmidlhey** [comment]
Divida  técnica de 

- Pedro Daia

- Pedro Daniel

- João Victor

**Comment by pdaniel37** [comment]
Todos os integrantes fizeram o protótipo de baixa fidelidade, foi criada uma pasta no drive para serem incluídos em uma documentação a ser confeccionada ao longo do projeto.
