### ISSUE TITLE
Coletar informações de commits

### ISSUE THREAD

**Issue by omateusp** [fga-eps-mds/2019.2-Git-Breakdown#29]
Receber informações de commits do repositório a partir da API do github.

**Comment by wdvictor** [comment]
Para esse problema, foi criado uma rota em routes.js, acessada apartir de "http://localhost:8888/commits", onde é dispadara um request to tipo GET  para o repositório BreakDown( usado como exemplo aqui), e recebe uma resposta do tipo json.
    O callback da função request, acessa alguns indices do arquivo, como nome do autor, data e conteúdo do commit, e adiciona esses datos a um arquivo txt

**Comment by pdaniel37** [comment]
Issue foi finalizada no commit c7143db e teve seu PR(#36) aceito.
