### ISSUE TITLE
US05 - Criar API Gateway

### ISSUE THREAD

**Issue by wdresende** [fga-eps-mds/2019.2-Git-Breakdown#33]
Eu como desenvolvedor, desejo cria a API Gateway para que haja a comunicação entre os microsserviços dentro do projeto.

- [x] Estruturar API Gateway
- [x] Conectar com os microsserviços já desenvolvidos

**Comment by pdaniel37** [comment]
O responsável pela issue deve organizar a estrutura de pastas que já contém os microsserviços já desenvolvidos nas issues #29 e #31.
