### ISSUE TITLE
Criar aba do Git Breakdown dentro do GitHub

### ISSUE THREAD

**Issue by wdvictor** [fga-eps-mds/2019.2-Git-Breakdown#48]
Eu como **usuário**, desejo **visualizar** o BreakDown nativamente com o GitHub , para **analisar o projeto** sem sair do GitHub.

- Checklist:
 - [x] Reconhecer quando o navegador está no github
 - [x] Reconhecer quando o usuário navega por um repositório

**Comment by lucasmidlhey** [comment]
Fechamos esta Issue devido a complexidade dela

Iremos dividir em duas novas issues
- Botao para pagina do github atualizando em cada click (listener)
- Botao redirecionar para uma blank page
