### ISSUE TITLE
Fazer teste de integração na API Gateway

### ISSUE THREAD

**Issue by lucasmidlhey** [fga-eps-mds/2019.2-Git-Breakdown#52]
Eu como **Desenvolvedor**, desejo **fazer testes de integração entre a API Gateway e os microsserciços**, para **aumentar a cobertura de testes**.

- Checklist:
 - [x] testar o microsserviço de commits
 - [x] testar o microsserviço de issues
 - [x] testar o microsserviço de pullrequests
 - [x] testar o microsserviço de branches

**Comment by pdaniel37** [comment]
Issue finalizada no commit 692a80d, aguardando o merge do PR(#54) para fechá-la.
