### ISSUE TITLE
Botão para página do github com icone atualizando por click

### ISSUE THREAD

**Issue by lucasmidlhey** [fga-eps-mds/2019.2-Git-Breakdown#64]
Eu como **usuário**, desejo **visualizar o git Breakdown na página do repositório**, para **acessar a extensão**.

- Checklist:
 - [x] botao na pagina
 - [x] manter botao quando atualiza pagina
- [x] manter botao quando clica em outra açao da pagina

**Comment by wdvictor** [comment]
A serious problem has been occurring during the implementation of this issue. It's the coexistence with the zenhub (probably with others extension too). The zenhub modify the DOM of the gitHub, including the entirely <body> tag and his class name, difficulting the GDB(Git BreakDown) to search for the necessary DOM elements that we need to find to modify(the nav tag with the code, issues, pull request buttons and etc.
       I'm trying to implement a Regular expression to find patterns(such as "env-production" in the body class name), but still now working.

**Comment by wdvictor** [comment]
The latest commit adds a code that lets the GDB button on-screen, independent of the change. But in some cases, like click on the zenhub or project button, the necessary class name needed to find the HTML tag, that we needed to include the GDB code, changes.
    The solution would be to search for the necessary tag using Regex.
    We will try this
