### ISSUE TITLE
Visualizar graficos em qualquer repositorio aberto

### ISSUE THREAD

**Issue by lucasmidlhey** [fga-eps-mds/2019.2-Git-Breakdown#65]
eu como **usuário** desejo **utilizar o gitbreakdown em qualquer repositório**, para que  **eu possa analisar diferentes repositórios**

- Checklist:
 - [x] capturar a url da página
 - [x] filtrar a url

**Comment by jbisinotti** [comment]
A filtragem da url tem como finalidade obter os atributos owner e repository, para que seja possível fazer requisições.
