### ISSUE TITLE
Criar Documento de Visão

### ISSUE THREAD

**Issue by pdaniel37** [fga-eps-mds/2019.2-Git-Breakdown#7]
Criação de um documento de visão que busca explicar o projeto de forma simples e direta, com foco para as funcionalidades e usabilidade. O corpo do documento deve possuir a seguinte estrutura:

- [x] Introdução
- [x] Posicionamento
- [x] Descrições da Parte Interessada e do Usuário
- [x] Visão Geral do Produto
- [x] Recursos do Produto
- [x] Restrições

Documentos para usar como base:
- https://fga-eps-mds.github.io/2019.1-Aix/projeto/2019/03/29/documento-de-visao/

**Comment by paulohgontijoo** [comment]
Introducao do documento criada

**Comment by paulohgontijoo** [comment]
Visao geral criada

**Comment by paulohgontijoo** [comment]
Implementado historico de revisoes, para melhor controle de versoes do documento.

**Comment by paulohgontijoo** [comment]
Criação do subitem oportunidade de negócios (em Posicionamento)
